version: '2'

services:

  # Apache 2.4
  feel_web:
    build: ./docker
    container_name: feel_web
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=<Your debug server name inside PHPStorm>"
    ports:
      - "10001:80"
      - "10002:22"
      - "10003:443"
    links:
      - feel_db
    volumes:
      - ./app:/var/www/app
    command: /usr/sbin/apache2ctl -DFOREGROUND -k start

  # MariaDB 10.3
  feel_db:
    image: "mariadb:10.3"
    container_name: feel_db
    ports:
      - 8306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_password
      
  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: feel_phpmyadmin
    links:
      - feel_db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: db_user
      PMA_PASSWORD: db_user_password
    ports:
      - '8080:80'
